algo = input('Digite algo? ')
tipo = type(algo)
an = algo.isalnum()
tp3 = algo.isnumeric()
tp4 = algo.isupper()
tp5 = algo.isspace()
print('O que você digitou é do tipo {}'.format(tipo))
print('O que você digitou é Alphanumerico? {}'.format(an))
print('É um número? {}'.format(tp3))
print('Esta em MAIUSCULO? {}'.format(tp4))
print('É um espaço? {}'.format(tp5))